-- ==============================================================================
-- ORACLE CHAMBER - DATABASE SETUP SCRIPT
-- Copy and paste this entire script into your Supabase SQL Editor and click RUN.
-- ==============================================================================

-- 1. Create the 'Pesan' (Messages) table
CREATE TABLE IF NOT EXISTS public."Pesan" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nama TEXT NOT NULL,
    teks TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public."Pesan" ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies for 'Pesan' (ALLOW ANONYMOUS)
DROP POLICY IF EXISTS "Allow public read access" ON public."Pesan";
CREATE POLICY "Allow public read access" ON public."Pesan" FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public insert access" ON public."Pesan";
CREATE POLICY "Allow public insert access" ON public."Pesan" FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access" ON public."Pesan";
CREATE POLICY "Allow public update access" ON public."Pesan" FOR UPDATE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow public delete access" ON public."Pesan";
CREATE POLICY "Allow public delete access" ON public."Pesan" FOR DELETE TO anon, authenticated USING (true);

-- 4. Setup Realtime
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;
ALTER PUBLICATION supabase_realtime ADD TABLE public."Pesan";

-- ==============================================================================
-- STORAGE SETUP (For Voice Notes and Images)
-- ==============================================================================

-- 1. Create the 'pub.voice note' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('pub.voice note', 'pub.voice note', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Create the 'pub.gambar' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('pub.gambar', 'pub.gambar', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Create Storage Policies for 'pub.voice note' bucket (ALLOW ANONYMOUS)
DROP POLICY IF EXISTS "Public Access for pub.voice note" ON storage.objects;
CREATE POLICY "Public Access for pub.voice note" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'pub.voice note');

DROP POLICY IF EXISTS "Public Insert for pub.voice note" ON storage.objects;
CREATE POLICY "Public Insert for pub.voice note" ON storage.objects FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'pub.voice note');

DROP POLICY IF EXISTS "Public Update for pub.voice note" ON storage.objects;
CREATE POLICY "Public Update for pub.voice note" ON storage.objects FOR UPDATE TO anon, authenticated USING (bucket_id = 'pub.voice note');

DROP POLICY IF EXISTS "Public Delete for pub.voice note" ON storage.objects;
CREATE POLICY "Public Delete for pub.voice note" ON storage.objects FOR DELETE TO anon, authenticated USING (bucket_id = 'pub.voice note');

-- 4. Create Storage Policies for 'pub.gambar' bucket (ALLOW ANONYMOUS)
DROP POLICY IF EXISTS "Public Access for pub.gambar" ON storage.objects;
CREATE POLICY "Public Access for pub.gambar" ON storage.objects FOR SELECT TO anon, authenticated USING (bucket_id = 'pub.gambar');

DROP POLICY IF EXISTS "Public Insert for pub.gambar" ON storage.objects;
CREATE POLICY "Public Insert for pub.gambar" ON storage.objects FOR INSERT TO anon, authenticated WITH CHECK (bucket_id = 'pub.gambar');

DROP POLICY IF EXISTS "Public Update for pub.gambar" ON storage.objects;
CREATE POLICY "Public Update for pub.gambar" ON storage.objects FOR UPDATE TO anon, authenticated USING (bucket_id = 'pub.gambar');

DROP POLICY IF EXISTS "Public Delete for pub.gambar" ON storage.objects;
CREATE POLICY "Public Delete for pub.gambar" ON storage.objects FOR DELETE TO anon, authenticated USING (bucket_id = 'pub.gambar');

-- ==============================================================================
-- DONE!
-- ==============================================================================
