-- ==============================================================================
-- ORACLE CHAMBER - DATABASE SETUP SCRIPT
-- Copy and paste this entire script into your Supabase SQL Editor and click RUN.
-- ==============================================================================

-- 1. Create the 'Pesan' (Messages) table
CREATE TABLE IF NOT EXISTS public."Pesan" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    nama TEXT NOT NULL,
    teks TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false NOT NULL
);

-- 2. Enable Row Level Security (RLS)
-- This is required by Supabase, but we will create policies to allow all access 
-- for this specific application since it's a shared chamber.
ALTER TABLE public."Pesan" ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies for 'Pesan'
-- Allow anyone to read messages
CREATE POLICY "Allow public read access" ON public."Pesan"
    FOR SELECT USING (true);

-- Allow anyone to insert new messages
CREATE POLICY "Allow public insert access" ON public."Pesan"
    FOR INSERT WITH CHECK (true);

-- Allow anyone to update messages (needed for edit and read receipts)
CREATE POLICY "Allow public update access" ON public."Pesan"
    FOR UPDATE USING (true);

-- Allow anyone to delete messages (needed for view once)
CREATE POLICY "Allow public delete access" ON public."Pesan"
    FOR DELETE USING (true);

-- 4. Setup Realtime
-- Enable realtime broadcasts and database changes for the 'Pesan' table
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;
ALTER PUBLICATION supabase_realtime ADD TABLE public."Pesan";

-- ==============================================================================
-- STORAGE SETUP (For Voice Notes and Images)
-- ==============================================================================

-- 1. Create the 'suara' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('suara', 'suara', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Create the 'gambar' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('gambar', 'gambar', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Create Storage Policies for 'suara' bucket
CREATE POLICY "Public Access for suara" ON storage.objects
    FOR SELECT USING (bucket_id = 'suara');

CREATE POLICY "Public Insert for suara" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'suara');

CREATE POLICY "Public Update for suara" ON storage.objects
    FOR UPDATE USING (bucket_id = 'suara');

CREATE POLICY "Public Delete for suara" ON storage.objects
    FOR DELETE USING (bucket_id = 'suara');

-- 4. Create Storage Policies for 'gambar' bucket
CREATE POLICY "Public Access for gambar" ON storage.objects
    FOR SELECT USING (bucket_id = 'gambar');

CREATE POLICY "Public Insert for gambar" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'gambar');

CREATE POLICY "Public Update for gambar" ON storage.objects
    FOR UPDATE USING (bucket_id = 'gambar');

CREATE POLICY "Public Delete for gambar" ON storage.objects
    FOR DELETE USING (bucket_id = 'gambar');

-- ==============================================================================
-- DONE!
-- ==============================================================================
