export interface DeckCategory {
    truth: string[];
    dare: string[];
    wildcard: string[];
    wildcardChance: number;
}

export interface GameDeck {
    light: DeckCategory;
    deep: DeckCategory;
    chaos: DeckCategory;
}

export const GAME_DECK: GameDeck = {
    light: {
        truth: [
            "Apa first impression kamu pas pertama kali kita ngobrol/kenal?",
            "Kalau kamu bisa pindah ke negara mana aja sekarang, kamu mau ke mana dan kenapa?",
            "Apa kebiasaan paling aneh yang sering kamu lakuin pas lagi sendirian di kamar?",
            "Sebutin 3 barang yang wajib ada di dekatmu pas lagi main HP/laptop!",
            "Apa lagu yang akhir-akhir ini sering banget kamu putar ulang?",
            "Pernah nggak kamu ngirim chat ke orang yang salah dan isinya memalukan? Ceritain!",
            "Kalau kamu disuruh makan satu jenis makanan aja seumur hidup, kamu pilih apa?",
            "Apa hal paling random yang pernah kamu beli secara online?",
            "Menurutmu, apa sifat terbaik yang kamu punya sebagai seorang teman?",
            "Pilih satu: Nggak bisa dengerin musik setahun atau nggak bisa nonton film/series setahun?",
            "Apa ketakutan paling konyol yang kamu punya sampai sekarang?",
            "Kalau hidupmu dibikin film, genre-nya apa dan siapa aktor/aktris yang meranin kamu?",
            "Apa hal terakhir yang bikin kamu ketawa ngakak sampai sakit perut?",
            "Pernah nggak kamu pura-pura tidur padahal lagi asik main HP? Gara-gara apa?",
            "Kalau kamu punya kekuatan super selama 24 jam, kamu mau ngapain aja?",
            "Apa topik obrolan favoritmu kalau lagi ngobrol sama orang baru?",
            "Sebutin satu hal yang menurut orang lain aneh, tapi menurutmu keren banget!",
            "Kalau kita ketemu langsung hari ini, menurutmu kita bakal ngapain aja?",
            "Apa emoji yang paling sering kamu pakai akhir-akhir ini?",
            "Ceritain satu kejadian apes tapi lucu yang pernah kamu alamin minggu ini!",
            "Apa hal paling memalukan yang pernah kamu lakuin di depan umum?",
            "Sebutin satu kebiasaan burukmu yang susah banget dihilangin!",
            "Pernah nggak kamu stalk sosmed mantan atau gebetan sampai ke postingan tahun jebot?",
            "Apa mimpi paling aneh yang pernah kamu alami dan masih kamu ingat?",
            "Kalau kamu cuma boleh dengerin satu genre musik seumur hidup, pilih apa?",
            "Apa makanan yang semua orang suka tapi kamu benci banget?",
            "Pernah nggak kamu bohong soal alasan telat balas chat? Apa alasannya?",
            "Sebutin satu hal yang bikin kamu gampang banget ketawa!",
            "Kalau kamu bisa jadi karakter di game atau film, kamu mau jadi siapa?",
            "Apa hal paling impulsif yang pernah kamu beli bulan ini?"
        ],
        dare: [
            "Kirim VN nyanyiin reff lagu yang lagi terngiang-ngiang di kepalamu sekarang!",
            "Kirim foto selfie dengan gaya paling absurd yang bisa kamu lakuin.",
            "Tulis pesan gombalan paling garing yang kamu tahu dan kirim ke aku.",
            "Ganti nama profil/kontakku di HP-mu jadi sesuatu yang lucu selama 24 jam.",
            "Kirim foto barang di sekitarmu yang warnanya paling mencolok.",
            "Kasih aku 3 pujian random pakai VN dengan nada sok asik.",
            "Kirim stiker WhatsApp/Line paling aneh yang kamu punya.",
            "Lakukan pose peace (✌️) di depan kamera dengan muka datar, lalu kirim fotonya.",
            "Kirim foto makanan atau minuman terakhir yang kamu konsumsi hari ini.",
            "Ceritain satu lelucon bapak-bapak (dad jokes) pakai VN.",
            "Kirim foto langit atau pemandangan di luar jendelamu sekarang.",
            "Kirim VN ngomong 'Halo, salam kenal!' pakai 3 aksen atau nada yang berbeda.",
            "Tirukan suara hewan peliharaan favoritmu lewat VN.",
            "Kirim foto outfit yang lagi kamu pakai sekarang (nggak usah kelihatan muka nggak apa-apa).",
            "Pilih satu emoji random dan jadikan itu balasan wajib untuk 3 pesanku berikutnya.",
            "VN suara ketawamu yang paling natural (atau dibikin-bikin juga boleh).",
            "Gambar sesuatu yang random di kertas/HP sejelek mungkin, terus kirim fotonya!",
            "Kirim VN ngomong kalimat tongue twister (misal: 'Kuku kaki kakekku kaku-kaku') secepat mungkin.",
            "Kirim foto barang di sekitarmu yang menurutmu paling nggak berguna.",
            "Ketik pesan pakai hidungmu: 'Aku jago banget main game ini' dan kirim ke aku.",
            "Kirim foto gaya rambutmu pas baru bangun tidur (atau acak-acak rambutmu sekarang dan foto)!",
            "VN nyanyiin lagu anak-anak (misal: Balonku) tapi pakai nada sedih.",
            "Kirim emoji random ke kontak ke-5 di WhatsApp/Line kamu, lalu screenshot reaksinya!",
            "Tulis namaku pakai tangan kiri (atau tangan non-dominan) di kertas, lalu kirim fotonya.",
            "Kirim VN ngomong 'Aku ini sebenarnya alien' pakai suara alien buatanmu.",
            "Fotoin isi kulkasmu sekarang juga!",
            "Kirim satu meme dari galerimu yang menurutmu paling lucu.",
            "Ganti foto profilmu pakai foto hewan lucu selama 1 jam.",
            "Kirim VN baca satu paragraf berita random dengan gaya pembaca berita TV.",
            "Kirim foto barang paling tua yang ada di kamarmu sekarang."
        ],
        wildcard: [
            "Bebas dari satu tantangan hari ini!",
            "Kamu berhak minta aku ngelakuin satu hal konyol buat kamu.",
            "Tukar giliran! Aku yang harus jawab pertanyaan Light dari kamu.",
            "Pilih satu foto dari galeriku (kalau ada) untuk kujadikan profil picture selama 1 jam.",
            "Kamu boleh minta aku kirim VN nyanyiin lagu pilihanmu.",
            "Kamu berhak nentuin topik obrolan kita selama 30 menit ke depan!",
            "Bebas dari hukuman kalau kamu nolak jawab satu pertanyaan hari ini.",
            "Kamu boleh minta aku ngirim foto selfie dengan gaya yang kamu tentuin.",
            "Aku harus nurutin satu permintaan sederhana kamu hari ini.",
            "Kamu berhak minta aku ceritain satu kejadian memalukan di masa laluku.",
            "Tukar giliran! Aku yang harus jawab 2 pertanyaan Truth berturut-turut.",
            "Kamu boleh minta aku VN ngucapin selamat malam/pagi dengan nada lucu.",
            "Aku harus pakai filter lucu pilihanmu kalau kita lagi video call/kirim foto.",
            "Kamu berhak minta aku ngirim foto makanan yang lagi aku pengen banget.",
            "Bebas pilih satu topik random yang harus kita bahas sekarang juga.",
            "Kamu boleh nanya satu pertanyaan random yang harus aku jawab dalam 5 detik.",
            "Aku harus ngirim VN gombalan paling maut yang aku tahu ke kamu.",
            "Kamu berhak minta aku ngirim foto barang paling unik di kamarku.",
            "Aku harus ceritain satu mimpi aneh yang pernah aku alamin.",
            "Kamu boleh minta aku ngucapin kata-kata penyemangat pakai VN buat kamu.",
            "Kamu berhak minta aku ngirim satu foto random dari galeriku (kamu sebutin nomor urutnya).",
            "Tukar giliran! Aku harus ngasih kamu satu pujian yang paling tulus.",
            "Kamu boleh nentuin satu kata yang nggak boleh aku sebut selama 10 menit ke depan.",
            "Aku harus ngirim VN niruin suara karakter kartun pilihanmu.",
            "Kamu berhak minta aku ceritain satu hal konyol yang terjadi hari ini.",
            "Bebas pilih satu game online ringan buat kita mainin bareng sekarang (misal: Gartic, Ludo).",
            "Kamu boleh nanya dua pertanyaan Truth berturut-turut ke aku.",
            "Aku harus ngirim foto layar HP-ku (homescreen) sekarang juga.",
            "Kamu berhak minta aku ngerekomendasiin satu film/series yang wajib kamu tonton.",
            "Tukar giliran! Aku harus ngelakuin satu Dare ringan pilihanmu."
        ],
        wildcardChance: 0.15
    },
    deep: {
        truth: [
            "Apa hal yang paling bikin kamu overthinking akhir-akhir ini?",
            "Menurutmu, apa batasan antara 'cuma teman' dan 'teman tapi mesra'?",
            "Pernah nggak kamu ngerasa nyaman banget ngobrol sama orang yang baru kamu kenal online? Kenapa?",
            "Apa satu hal yang bikin kamu gampang ilfeel pas lagi PDKT sama orang?",
            "Kalau kamu disuruh deskripsiin hubungan kita sekarang pakai satu kata, kata apa yang kamu pilih?",
            "Apa trauma masa lalu yang masih sering bikin kamu ragu buat buka hati?",
            "Menurutmu, apa hal paling menarik dari obrolan-obrolan kita selama ini?",
            "Pernah nggak kamu ngerasa cemburu pas aku lagi cerita soal orang lain?",
            "Apa kualitas terpenting yang harus dimiliki seseorang biar kamu bisa percaya sama dia?",
            "Kalau kita bisa ketemu langsung besok, apa hal pertama yang pengen kamu obrolin/lakuin bareng?",
            "Apa hal yang paling kamu takutin dalam membangun sebuah hubungan (baik pertemanan atau lebih)?",
            "Pernah nggak kamu ngerasa 'klik' sama seseorang, tapi situasinya nggak memungkinkan buat bareng?",
            "Apa satu hal yang pengen banget kamu ceritain ke aku, tapi selama ini kamu tahan?",
            "Menurutmu, LDR atau hubungan jarak jauh (termasuk virtual) itu worth it nggak sih?",
            "Gimana caramu nunjukin rasa peduli ke orang yang jaraknya jauh dari kamu?",
            "Apa hal yang paling bikin kamu ngerasa kesepian, dan gimana caramu ngatasinnya?",
            "Pernah nggak kamu berharap hubungan kita ini bisa lebih dari sekadar yang sekarang?",
            "Apa satu pertanyaan yang dari dulu pengen banget kamu tanyain ke aku?",
            "Menurutmu, apa hal yang bikin orang bisa nyaman cerita hal-hal personal ke kamu?",
            "Kalau suatu saat kita lost contact, apa satu hal dari aku yang bakal kamu ingat?",
            "Apa hal yang paling bikin kamu merasa gagal, dan gimana kamu bangkit dari situ?",
            "Pernah nggak kamu ngerasa kehilangan jati diri demi diterima orang lain?",
            "Apa penyesalan terbesarmu dalam hal pertemanan atau asmara?",
            "Menurutmu, apa hal yang paling susah dimaafkan dari sebuah kesalahan?",
            "Kapan terakhir kali kamu menangis, dan apa alasannya?",
            "Apa satu hal yang selalu bikin kamu merasa insecure kalau lagi ngumpul sama orang banyak?",
            "Pernah nggak kamu ngerasa kesepian di tengah keramaian? Ceritain momennya.",
            "Apa ekspektasi terbesar orang tuamu yang bikin kamu merasa terbebani?",
            "Kalau kamu bisa ngulang satu hari di masa lalu, hari apa yang kamu pilih dan kenapa?",
            "Apa hal yang paling kamu syukuri dari hidupmu saat ini?",
            "Menurutmu, apakah cinta pada pandangan pertama itu ada, atau cuma ketertarikan fisik aja?",
            "Apa hal yang paling bikin kamu ilfeel dari seseorang pas lagi proses pendekatan?",
            "Pernah nggak kamu bertahan di hubungan (teman/pacar) yang toxic? Kenapa kamu bertahan saat itu?",
            "Apa satu prinsip hidup yang nggak akan pernah kamu langgar demi siapapun?",
            "Kalau kamu tahu besok adalah hari terakhirmu, apa yang bakal kamu lakuin hari ini?",
            "Apa hal yang paling kamu harapkan dari seseorang yang lagi dekat sama kamu sekarang?",
            "Pernah nggak kamu ngerasa iri sama pencapaian teman terdekatmu? Gimana caramu ngatasinnya?",
            "Apa satu hal yang pengen banget kamu ubah dari sifat aslimu?",
            "Menurutmu, apa arti kebahagiaan yang sesungguhnya buat kamu pribadi?",
            "Kalau kamu bisa nulis satu pesan untuk dirimu di masa depan (5 tahun lagi), apa isinya?"
        ],
        dare: [
            "Kirim VN ceritain first impression kamu ke aku dengan jujur dan detail.",
            "Kirim foto lama kamu yang paling punya banyak kenangan, dan ceritain alasannya.",
            "Jujur tentang satu hal yang bikin kamu penasaran banget soal aku.",
            "Kirim VN bilang 'Aku seneng bisa kenal kamu' dengan nada paling tulus.",
            "Kirim screenshot chat history kita yang menurutmu paling seru atau gemes.",
            "Ceritain satu hal yang bikin kamu insecure, biar aku bisa dengerin dan kasih semangat.",
            "Tulis 3 hal yang bikin kamu nyaman ngobrol sama aku.",
            "Kirim foto mata kamu dari jarak dekat, tanpa filter.",
            "Ceritakan satu momen di mana kamu ngerasa bener-bener butuh teman cerita.",
            "Kirim VN nyanyiin sedikit bagian dari lagu yang menurutmu 'aku banget'.",
            "Tulis pesan singkat buat aku baca pas aku lagi ngerasa down.",
            "Ceritain momen pas kamu sadar kalau kita ternyata nyambung banget ngobrolnya.",
            "Kirim lagu yang liriknya paling pas buat gambarin perasaanmu akhir-akhir ini.",
            "Kirim VN ceritain satu hal yang paling kamu takutin dari perpisahan.",
            "Jujur ke aku: Apa satu hal dari sikapku yang kadang bikin kamu bingung?",
            "Kirim foto barang di sekitarmu yang punya nilai sentimental tinggi buatmu.",
            "Ceritain satu momen di mana kamu ngerasa bener-bener dihargai oleh seseorang.",
            "VN ceritain rencanamu buat kita kalau suatu hari nanti kita beneran bisa ketemuan.",
            "Tulis satu paragraf tentang apa arti kehadiran orang-orang virtual di hidupmu.",
            "Kirim VN ceritain satu harapan terbesarmu buat dirimu sendiri di tahun ini.",
            "Kirim VN ceritain satu hal yang paling kamu sesali pernah kamu lakuin ke orang lain.",
            "Tulis 3 hal yang menurutmu paling berharga dalam hidupmu saat ini, dan kirim ke aku.",
            "Kirim foto barang yang paling punya kenangan sedih buatmu, dan ceritain singkat alasannya.",
            "Jujur ke aku: Apa satu hal yang bikin kamu ngerasa takut buat komitmen?",
            "Kirim VN nyanyiin lagu yang biasanya kamu dengerin pas lagi sedih/galau.",
            "Ceritain satu momen di mana kamu merasa sangat bangga sama dirimu sendiri.",
            "Tulis satu pesan singkat untuk orang di masa lalumu yang belum sempat kamu sampaikan.",
            "Kirim screenshot lagu yang paling sering kamu putar di Spotify/Apple Music bulan ini.",
            "Jujur tentang satu hal yang sering bikin kamu overthinking di malam hari.",
            "Kirim VN ceritain satu mimpi terbesarmu yang belum pernah kamu ceritain ke siapa-siapa.",
            "Tulis 3 sifat dari diriku yang menurutmu paling menarik atau bikin nyaman.",
            "Ceritain satu kejadian di masa kecil yang masih membekas banget sampai sekarang.",
            "Kirim foto langit malam ini, dan ceritain apa yang lagi kamu rasain sekarang.",
            "Jujur ke aku: Pernah nggak kamu ngerasa pengen nyerah sama keadaan? Gimana kamu lewatinnya?",
            "Kirim VN baca satu quotes favoritmu yang selalu bikin kamu semangat lagi.",
            "Ceritain satu hal yang bikin kamu merasa sangat dicintai oleh seseorang (keluarga/teman/pasangan).",
            "Tulis satu paragraf tentang apa arti 'rumah' buat kamu (bukan bangunan fisik).",
            "Kirim foto sudut favorit di kamarmu, dan ceritain kenapa kamu suka tempat itu.",
            "Jujur tentang satu hal yang pengen banget kamu capai sebelum umur 30 tahun.",
            "Kirim VN ceritain satu momen di mana kamu merasa sangat beruntung masih hidup."
        ],
        wildcard: [
            "Deep Talk Time: Kamu boleh tanya satu pertanyaan apa aja, dan aku harus jawab jujur 100%.",
            "Kamu berhak minta aku ceritain satu rahasia terdalamku yang jarang orang tahu.",
            "Kita berdua harus saling kirim VN apresiasi buat satu sama lain selama 1 menit.",
            "Kamu boleh minta aku jujur tentang satu hal yang bikin aku ragu soal banyak hal.",
            "Skip satu pertanyaan Deep kalau kamu ngerasa belum siap jawab.",
            "Kamu boleh minta aku jujur tentang first impression-ku ke kamu.",
            "Kita harus luangin waktu 10 menit buat ngobrolin 'kita ini sebenarnya apa' atau arah hubungan kita.",
            "Kamu berhak minta aku nulis pesan panjang tentang hal-hal yang aku suka dari kamu.",
            "Aku harus jujur tentang ketakutan terbesarku soal kehilangan orang yang aku peduliin.",
            "Kamu boleh minta aku ceritain satu hal yang bikin aku ngerasa bersalah di masa lalu.",
            "Kita berdua harus saling share satu lagu yang liriknya paling ngena buat situasi kita sekarang.",
            "Kamu berhak minta aku ngirim VN ceritain kenapa aku nyaman ngobrol sama kamu.",
            "Aku harus jujur tentang satu hal yang bikin aku bangga bisa kenal kamu.",
            "Kamu boleh minta aku ceritain satu momen pas aku ngerasa paling rapuh.",
            "Kita harus saling share satu foto masa kecil dan ceritain kenangannya.",
            "Kamu berhak minta aku jujur tentang apa yang paling aku butuhin dari seorang teman/partner saat ini.",
            "Aku harus ceritain satu hal yang bikin aku ngerasa paling disayang sama orang terdekatku.",
            "Kamu boleh minta aku ngirim VN doa atau harapan khusus buat kamu hari ini.",
            "Kita berdua harus saling share satu hal yang pengen kita capai dalam waktu dekat.",
            "Kamu berhak minta aku jujur tentang satu hal yang bikin aku ngerasa insecure pas ngobrol sama orang baru.",
            "Aku harus ceritain satu momen di mana aku ngerasa bersyukur banget ada internet yang bisa nemuin kita.",
            "Kamu berhak minta aku jujur tentang satu hal yang paling aku takutin dalam hidup.",
            "Kita harus saling share satu cerita tentang patah hati terberat yang pernah kita alamin.",
            "Kamu boleh minta aku ngirim VN nyanyiin lagu yang paling bermakna buatku.",
            "Aku harus ceritain satu hal yang paling bikin aku ngerasa insecure soal penampilanku.",
            "Kamu berhak minta aku jujur tentang apa yang paling aku cari dari seorang pasangan hidup.",
            "Kita berdua harus saling share satu hal yang paling kita syukuri dari pertemuan kita.",
            "Kamu boleh minta aku ceritain satu momen di mana aku merasa sangat kecewa sama diriku sendiri.",
            "Aku harus jujur tentang satu hal yang pengen banget aku perbaiki dari sifatku.",
            "Kamu berhak minta aku ngirim foto barang yang paling berharga buatku dan ceritain alasannya.",
            "Kita harus saling share satu mimpi yang terpaksa kita kubur dalam-dalam.",
            "Kamu boleh minta aku jujur tentang satu hal yang bikin aku susah percaya sama orang lain.",
            "Aku harus ceritain satu momen di mana aku merasa sangat kesepian, dan gimana aku ngatasinnya.",
            "Kamu berhak minta aku ngirim VN ceritain satu pelajaran hidup paling berharga yang pernah aku dapet.",
            "Kita berdua harus saling share satu hal yang paling kita harapkan dari masa depan.",
            "Kamu boleh minta aku jujur tentang satu hal yang bikin aku ngerasa 'hidup' banget.",
            "Aku harus ceritain satu momen di mana aku merasa sangat bersyukur punya keluarga/teman yang supportif.",
            "Kamu berhak minta aku ngirim foto tempat yang paling pengen aku kunjungin buat healing.",
            "Kita harus saling share satu hal yang paling kita sesali dari masa remaja kita.",
            "Kamu boleh minta aku jujur tentang satu hal yang pengen banget aku denger dari seseorang saat ini."
        ],
        wildcardChance: 0.10
    },
    chaos: {
        truth: [
            "Apa bagian tubuhku yang paling bikin kamu bergairah walau cuma lihat di foto?",
            "Kapan terakhir kali kamu mikirin aku pas lagi 'sendiri'?",
            "Apa fantasi terliarmu tentang kita pas ketemu nanti?",
            "Apa pakaian (atau ketiadaan pakaian) yang paling pengen kamu lihat aku pakai?",
            "Apa hal paling nakal yang pengen kamu lakuin ke aku pas video call?",
            "Suara/desahan seperti apa dari aku yang paling bikin kamu merinding?",
            "Apa chat paling kotor/spicy yang pernah kita obrolin yang bikin kamu sange?",
            "Kalau kita lagi di satu kasur sekarang, apa yang bakal kamu lakuin pertama kali?",
            "Apa hal kinky yang pengen banget kamu coba sama aku?",
            "Bagian tubuh mana dari kamu yang paling pengen aku sentuh/cium duluan?",
            "Pernahkah kamu berfantasi tentang aku pas lagi di tempat umum?",
            "Apa 'turn on' terbesarmu saat kita lagi LDR-an?",
            "Gimana caramu 'menyelesaikan' diri sendiri pas lagi kangen banget sama aku?",
            "Apa posisi seks yang paling pengen kamu coba pas kita ketemu?",
            "Apa hal paling berani yang pernah kamu lakuin buat godain aku lewat chat?",
            "Pas lagi video call berdua, pernahkah kamu diam-diam nyentuh dirimu sendiri sambil ngeliatin aku?",
            "Apa jenis pakaian dalam yang menurutmu paling seksi kalau aku pakai pas kita VC?",
            "Kalau kita punya waktu 24 jam berdua di hotel tanpa ada yang ganggu, apa rundown kasarnya?",
            "Apa kata-kata kotor (dirty talk) yang paling pengen kamu denger langsung dari bisikanku?",
            "Bagian tubuh mana dari aku yang paling sering muncul di fantasi liarmu pas kita lagi jauh?"
        ],
        dare: [
            "Kirim VN desahan pelan atau panggil namaku dengan nada paling menggoda.",
            "Kirim foto (View Once) bagian tubuhmu yang paling seksi menurutmu.",
            "Buka satu kancing baju/resleting dan kirim fotonya sekarang.",
            "Deskripsiin secara detail (lewat teks/VN) gimana cara kamu mau 'main' sama aku malam ini.",
            "Kirim foto kamu gigit bibir bawah dengan tatapan nakal.",
            "Pakai pakaian dalam favoritmu (atau tanpa pakaian dalam) dan kasih tau aku detailnya.",
            "Kirim VN ceritain fantasi basah terakhirmu tentang aku.",
            "Lakukan sesuatu yang bikin kamu 'turn on' selama 1 menit sambil chat aku.",
            "Kirim foto leher atau tulang selangkamu dari jarak dekat.",
            "Kasih aku instruksi nakal buat aku lakuin sekarang juga.",
            "Kirim VN dirty talk paling liar yang bisa kamu pikirin selama 30 detik.",
            "Tunjukkan (lewat foto/video VO) mainan seks atau benda yang sering kamu pakai.",
            "Kirim foto tanganmu seolah-olah lagi nyentuh aku.",
            "Ceritain detail apa yang bakal kamu lakuin ke aku kalau aku lagi terikat di kasur.",
            "Kirim pesan teks paling nakal yang bikin aku langsung pengen ketemu.",
            "Kirim VN desahan pelan seolah-olah aku lagi nyium lehermu dari belakang.",
            "Kirim foto (View Once) siluet tubuhmu di depan cermin dengan pencahayaan minim.",
            "Deskripsiin lewat chat, step-by-step, apa yang bakal kamu lakuin ke aku pas kita pertama kali masuk kamar berdua.",
            "Kirim foto (View Once) jejak lipstik/ciuman di tangan atau lehermu buat aku.",
            "VN ceritain satu mimpi basah paling detail yang pernah kamu alamin tentang kita."
        ],
        wildcard: [
            "Kamu pegang kendali: Suruh aku lakuin satu hal nakal (lewat VN/Foto/Video VO) sekarang juga.",
            "Free Pass: Kamu boleh minta foto View Once apa aja dari aku.",
            "Roleplay Time: Kita berdua harus roleplay nakal selama 10 menit ke depan.",
            "Kamu boleh minta aku kirim VN mendesah sebut namamu.",
            "Tukar giliran! Aku yang harus ngelakuin dare Chaos pilihanmu.",
            "Kamu boleh minta aku ngirim foto (View Once) bagian tubuhku yang paling kamu suka.",
            "Kita harus sexting selama 15 menit tanpa boleh ngirim foto, cuma pakai kata-kata yang paling menggoda.",
            "Kamu berhak minta aku ngirim VN dirty talk dengan skenario pilihanmu.",
            "Aku harus nurutin satu perintah nakal kamu selama sesi video call berikutnya.",
            "Kamu boleh minta aku pakai pakaian dalam warna tertentu pas kita ketemu nanti.",
            "Kita berdua harus saling share satu fantasi liar yang belum pernah kita ceritain.",
            "Kamu berhak minta aku ngirim foto (View Once) pose menggoda di atas kasur.",
            "Aku harus ceritain detail apa yang bakal aku lakuin ke kamu kalau kamu lagi mandi.",
            "Kamu boleh minta aku ngirim VN suara ciuman paling basah yang bisa aku buat.",
            "Kita harus saling share satu hal kinky yang pengen kita coba bareng.",
            "Kamu berhak minta aku ngirim foto (View Once) paha atau perutku.",
            "Aku harus jujur tentang satu hal nakal yang sering aku pikirin pas ngeliat fotomu.",
            "Kamu boleh minta aku ngirim VN ceritain gimana rasanya kalau aku nyentuh kamu di sana.",
            "Kita berdua harus saling share satu tempat ekstrem yang pengen kita jadiin tempat 'main'.",
            "Kamu berhak minta aku ngirim foto (View Once) dengan tatapan paling menggoda.",
            "Aku harus ceritain detail apa yang bakal aku lakuin ke kamu kalau kita lagi di bioskop sepi.",
            "Kamu boleh minta aku ngirim VN desahan panjang seolah-olah aku lagi klimaks."
        ],
        wildcardChance: 0.10
    }
};
